# ==================================================
# ArchClone Exclusion Rules
# ==================================================

# Cache
.cache/

# Trash
.local/share/Trash/

# Logs
*.log

# Swap files
*.swp
*.swo

# Temporary files
*.tmp
*.temp

# Python
__pycache__/
*.pyc

# Node
node_modules/

# Browser cache
.mozilla/firefox/*/cache2/
.cache/mozilla/
.cache/chromium/
.cache/google-chrome/
.cache/BraveSoftware/

# Steam
.local/share/Steam/

# Thumbnails
.cache/thumbnails/

# Package cache
.cache/pip/
